### PR TITLE
ivy: bring panics back to main goroutine in pfor

### LINKED ISSUE #103: pfor doesn't catch panics
@rsc The parallel execution introduced by #84 doesn't seem to guard against the possibility of legitimate exceptions such as division by zero.

For example:

```
% ivy
1 / 200 6 rho 0
panic: division by zero

goroutine 46 [running]:
robpike.io/ivy/value.Errorf(...)
	/home/rogpeppe/src/go/src/github.com/rsc/ivy/value/value.go:49
robpike.io/ivy/value.init.0.func13({0x57cd88?, 0x543509?}, {0x57cce8?, 0xc000126400?}, {0x57cce8?, 0xc000126440?})
	/home/rogpeppe/src/go/src/github.com/rsc/ivy/value/binary.go:277 +0xab
robpike.io/ivy/value.(*binaryOp).EvalBinary(0xc0001242a0, {0x57cab8, 0xc000125260}, {0x57cd88, 0x632148}, {0x57cd88, 0x632140})
	/home/rogpeppe/src/go/src/github.com/rsc/ivy/value/eval.go:112 +0x2a8
robpike.io/ivy/exec.(*Context).EvalBinary(0xc000125260, {0x57cd88, 0x632148}, {0x543509, 0x1}, {0x57cd88, 0x632140})
	/home/rogpeppe/src/go/src/github.com/rsc/ivy/exec/context.go:172 +0x189
robpike.io/ivy/value.binaryMatrixOp.func1(0x0?, 0x4b0)
	/home/rogpeppe/src/go/src/github.com/rsc/ivy/value/eval.go:597 +0xfb
robpike.io/ivy/value.pfor.func1()
	/home/rogpeppe/src/go/src/github.com/rsc/ivy/value/eval.go:188 +0x67
created by robpike.io/ivy/value.pfor
	/home/rogpeppe/src/go/src/github.com/rsc/ivy/value/eval.go:186 +0x107
```

### PR DESCRIPTION
**Pull request by rsc**
This handles panics for problems like 'division by zero'.

Fixes #103.

### CODE REVIEW

File: value/eval.go [hunk 1]
```diff
@@ -179,16 +178,27 @@ func pfor(ok bool, size, n int, f func(lo, hi int)) {
...
 		lo, hi := i*n/p, (i+1)*n/p
-		wg.Add(1)
 		go func() {
-			defer wg.Done()
+			defer sendRecover(c)
 			f(lo, hi)
 		}()
 	}
-	wg.Wait()
+	var bad interface{}
```
Comment (robpike) [inline value/eval.go:189]: surely s/bad/err/

File: testdata/exec_fail.ivy [hunk 2]
```diff
@@ -47,3 +47,9 @@ x
 # index must be integer
 1 2[1 2 log 2]
 	X
+
+1 / 0
+	X
+
+1 / 2 2 rho 0
```
Comment (robpike) [inline testdata/exec_fail.ivy:54]: not sure these tests trigger it. i did

(100 100 rho 1) / (100 100 rho 0)

and checked that the new code ran.

Comment (rsc) [reply testdata/exec_fail.ivy:54]: It's true that `1 / 2 2 rho 0` doesn't trigger it in ordinary ivy, but it does in the test.
'go test' runs with maximal parallelism, via value.MaxParallelismForTesting.

**Review by robpike — APPROVED** [review]
